### ISSUE TITLE
你好，一加的主题设置问题

### ISSUE THREAD

**Issue by WoKee** [dadaewq/Dark-Mode-Switch#2]
开启/关闭深色主题时，系统主题会显示对应的 白色/黑色。 但系统界面并未应用相应的主题，需要进入设置重新点击主题设置才会生效。 一加3  android 9.0。 希望能跟进处理下。相应的我可以参与测试。

**Comment by dadaewq** [comment]
一加系统在设置里有对应的开关

**Comment by WoKee** [comment]
> 一加系统在设置里有对应的开关

系统设置里面显示已经应用了黑色主题，但UI依旧是白色。 
![1](https://user-images.githubusercontent.com/10387578/104538796-8a750380-5657-11eb-8e0d-9f39bb905840.jpg)
![2](https://user-images.githubusercontent.com/10387578/104538798-8b0d9a00-5657-11eb-9f54-60d70f1e6bba.jpg)
![3](https://user-images.githubusercontent.com/10387578/104538803-8c3ec700-5657-11eb-8e8f-7bbea91db4ba.jpg)

**Comment by WoKee** [comment]
> 一加系统在设置里有对应的开关
系统设置里面显示已经应用了黑色主题，但UI依旧是白色。
![1](https://user-images.githubusercontent.com/10387578/104538979-c4dea080-5657-11eb-8aa2-e8f52a6eb6cc.jpg)
![2](https://user-images.githubusercontent.com/10387578/104538987-c740fa80-5657-11eb-9ba9-65a2b7042fd5.jpg)
![3](https://user-images.githubusercontent.com/10387578/104538991-c7d99100-5657-11eb-96db-32813d7611f2.jpg)
