### ISSUE TITLE
死马的酷安小编把你应用下了

### ISSUE THREAD

**Issue by ghost** [dadaewq/Dark-Mode-Switch#4]
我宣布酷安小编的妈天打五雷轰，永世不得超生

**Comment by zanjie1999** [comment]
所以有备份的apk吗（

**Comment by xiao-k233** [comment]
这作者也没个action（
有个action起码知道怎么编译

**Comment by zanjie1999** [comment]
## 可以使用ADB来设置暗黑模式，哪怕是上古android都可以
### 黑
adb shell settings put secure ui_night_mode 2
### 白
adb shell settings put secure ui_night_mode 1
### 自动
adb shell settings put secure ui_night_mode 0
### 设置完要重启Android才能生效
adb shell reboot

**Comment by xiao-k233** [comment]
[深色模式切换_2.7.2.zip](https://github.com/user-attachments/files/16667470/_2.7.2.zip)
52破解的

**Comment by ghost** [comment]
> 所以有备份的apk吗（

No

**Comment by ghost** [comment]
what

**Comment by ghost** [comment]
怎么closed了
